"""

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""

def calc_fib_sum(n):
	s = 2
	a = 1
	b = 2
	c = a + b
	while(b + c <= n):
		(a, b) = (b, c)
		c = b + a
		if c % 2 == 0:
			s += c

	print (s)
	return s


calc_fib_sum(90)
calc_fib_sum(4000000)